version: '3.4'

services:
  orgsource:
    image: orgsource
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 4100:4100
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
